### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by analognightmare** [hexgolems/td#16]
- [ ] new buff icons
- [ ] game must be faster
- [ ] bigger map
- [ ] cheat mode for testing
- [ ] poison
- [ ] slpash
- [ ] chain
- [ ] multi arrow
- [ ] no blue background anymore
